language: go
sudo: false
go:
- 1.8
before_install:
#- go get golang.org/cmd/vet
- go get golang.org/x/tools/cmd/cover
script:
- go test -v github.com/starkandwayne/shield/...
- go test -race github.com/starkandwayne/shield/...
notifications:
  email:
    on_success: never
    on_failure:
    - jhunt@starkandwayne.com
    - qanx@starkandwayne.com
    - krutten@starkandwayne.com
    - dbell@starkandwayne.com
  slack:
    secure: mHnp3G2d94h161sKJRnywZdLwguBMeZ0794Leh14Mychmpgb1y7XQPbZsMOuOJxFq6X2PAMg2k8JZaAYVeMcAKeACr9wrP75drw1NDQCvyxMHsEVN+wcEC5RIoy4BrfuNSxcty1GAGiVsCe41BUmWgoFqFepzmYwgpVfRX/99LdYkMQeWvmuxYn29VYiNrW/gcvPI0LLEzpPAb1lBVHRVRY1v3k4FHZL93VPB6Yo9BC+ViEisDEBtB+aFYFDbuBHXp4NLzlrrv1iXo7UIW/vypXnGi600248/VDnaKmB1B/zwaz4ucvheOCQ4ttsCj4T+PfkFoyesiOTfOX/aBE2GxmWrxzFnvwwMfd/xr3uclBJIAWqVNRf48ZjE1dKPvUO761jnIoHdN0KJ621/oXun5uucyF1IwQQzJhzvtv8/RO914Vj5EsuQrmdfYMyAZ1bpRLY/gNRzO0daWVmt8gonQdRVoG+VV2LNdXv5AsiltKT/R6nmZXRW0TRW5LJIgRCqlXOERvWkIo4exZCnPCBFDeQgDAH8oVR3acr1L3PPw8c4BUphengetx0dQH5jdcMC31CVEkTGAFz0PXD2Pj5jBf2JH8NlJzO2CqArHu6N3uIKf8CTRVz+3LlLp5yrsCedah0AINcYRInKczNySvcgBf7UoIKwJaCJ21Fcy/XnuQ=
