version: '3'
services:
  vault:
    image: vault:1.0.2
    ports: [8200]
    networks: [internal]
    environment:
      VAULT_API_ADDR: http://127.0.0.1:8200
      VAULT_LOCAL_CONFIG: >-
        {
          "disable_mlock": 1,
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address":     "0.0.0.0:8200",
              "tls_disable": 1
            },
          },
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - 'vault-data:/vault/file'
    command: 
      - vault
      - server
      - "-config"
      - "/vault/config/local.json"
  


  core:
    depends_on:
      - vault
    image: 'shieldproject/shield:dev'
    ports: ['9009:80']
    networks: [internal]
    command: ['/shield/init/core']
    environment:
      SHIELD_VAULT_ADDRESS: http://vault:8200
      SHIELD_API_BIND: core:80
      SHIELD_CORE: localcore
    volumes:
      - 'shield-data:/var/shield'
      - 'shield-etc:/etc/shield'

  demo:
    depends_on:
      - core
      - webdav
    image: 'shieldproject/demo:dev'
    ports: ['9008:80']
    networks: [internal]
    volumes:
      - 'demo-data:/www'

  rabbitmq-source:
    image: shieldproject/rabbitmq:demo
    hostname: rabbitmq-source
    networks: [internal]
    ports:
      - 5672:5672
      - 15672:15672

  rabbitmq-dest:
    image: rabbitmq:3-management
    hostname: rabbitmq-dest
    networks: [internal]
    ports:
      - 5673:5672
      - 15673:15672

  agent:
    depends_on:
      - core
      - webdav
    image: 'shieldproject/shield:dev'
    ports: [5444]
    networks: [internal]
    command: ['/shield/init/agent']
    environment:
      SHIELD_API:        'http://core:80'
      SHIELD_AGENT_NAME: 'demo-shield-agent'
    volumes:
      - 'shield-data:/var/shield'
      - 'shield-etc:/etc/shield'
      - 'demo-data:/www'

  webdav:
    image: 'shieldproject/webdav:dev'
    ports: ['9007:80']
    networks: [internal]
    environment:
      USERNAME: webdav
      PASSWORD: password
    volumes:
      - 'webdav-data:/var/webdav'

networks:
  internal:

volumes:
  vault-data:
  shield-data:
  shield-etc:
  webdav-data:
  demo-data:
